2023-04-24 02:44:45,891 - root - DEBUG - 127.0.0.1 - - [24/Apr/2023 02:44:45] "GET / HTTP/1.1" 200 -2023-04-24 03:24:23,399 - root - ERROR - type object 'QProcess' has no attribute 'Running'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 342, in create_server
    if broker_process.state() == QProcess.Running:
AttributeError: type object 'QProcess' has no attribute 'Running'
2023-04-24 03:59:41,699 - root - ERROR - [Errno 13] Permission denied: '/etc/mosquitto/mosquitto.conf'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 360, in create_server
    with open(conf_file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/etc/mosquitto/mosquitto.conf'
2023-04-24 04:02:04,003 - root - ERROR - name 'ip_address' is not defined
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 354, in create_server
    os.system(f"pkexec echo 'listener {ip_address}:{port_number}' > /etc/mosquitto/mosquitto.conf")
NameError: name 'ip_address' is not defined
2023-04-24 04:06:34,953 - root - ERROR - 'PyQt6.QtCore.pyqtBoundSignal' object has no attribute 'start'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 359, in create_server
    self.broker_process.finished.start("mosquito",["-c","/etc/mosquitto/mosquitto.conf"])
AttributeError: 'PyQt6.QtCore.pyqtBoundSignal' object has no attribute 'start'
2023-04-24 04:14:58,473 - root - ERROR - module 'os' has no attribute 'getCwd'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 359, in create_server
    self.broker_process.start("mosquito",["-c",f"{os.getCwd()}/mosquitto.conf"])
AttributeError: module 'os' has no attribute 'getCwd'
2023-04-24 04:22:28,690 - root - ERROR - 'QLineEdit' object has no attribute 'settext'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 354, in create_server
    self.server_ip_input.settext("127.0.0.1")
AttributeError: 'QLineEdit' object has no attribute 'settext'
2023-04-24 04:24:29,054 - root - ERROR - 'NoneType' object has no attribute 'start'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 360, in create_server
    self.server_http_process.start("mosquitto", [ "-p", self.server_port_input.text()])
AttributeError: 'NoneType' object has no attribute 'start'
2023-04-25 06:32:13,894 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect(self.server_ip_input.text(),int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:36:48,876 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:47:11,152 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:53:42,566 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:57:17,138 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 367, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:59:50,017 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 800, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:04:42,047 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 367, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 07:23:52,591 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 809, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:26:05,577 - root - ERROR - 'MainWindow' object has no attribute 'tcp_server'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 382, in create_server
    elif self.tcp_server:
AttributeError: 'MainWindow' object has no attribute 'tcp_server'
2023-04-25 07:55:12,608 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 820, in closeEvent
    self.broker_process.terminate()
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:56:29,664 - root - ERROR - 'MainWindow' object has no attribute 'mqtt_server_client'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 383, in create_server
    self.mqtt_server_client.disconnect()
AttributeError: 'MainWindow' object has no attribute 'mqtt_server_client'
2023-04-25 08:07:53,393 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 835, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:11:21,577 - root - ERROR - wrapped C/C++ object of type QUdpSocket has been deleted
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 384, in create_server
    self.server_udp_socket.deleteLater()
RuntimeError: wrapped C/C++ object of type QUdpSocket has been deleted
2023-04-25 08:11:34,802 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 835, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:14:00,165 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:25:57,563 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:29:15,725 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:34:33,027 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 845, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:37:47,949 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 850, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:38:56,390 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 852, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:40:21,286 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 855, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:42:10,103 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 855, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:44:36,313 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 856, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:51:43,470 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 855, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:56:54,371 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 863, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:58:55,109 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 863, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:00:09,373 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 864, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:02:21,952 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 865, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:03:00,157 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 864, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:04:18,769 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 865, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:08:30,963 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 867, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:10:08,062 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:10:48,405 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:25:49,642 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:29:51,783 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 795, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 876, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:31:45,055 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 895, in closeEvent
    if self.server_http_process.state() != QProcess.ProcessState.NotRunning:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:32:17,033 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 795, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 876, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:32:17,816 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 795, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 876, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:32:28,087 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 898, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:36:55,925 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 796, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:36:58,252 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 796, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:37:08,290 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 899, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:39:32,166 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:33,366 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:34,022 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:34,678 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:35,182 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:35,646 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:36,102 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:36,894 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:37,318 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:44,182 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:13,470 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:19,054 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:19,831 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,206 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,478 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,670 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,878 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:46,957 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 900, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:43:27,077 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:27,825 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:28,089 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:28,281 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:28,449 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:44:03,496 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 901, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:45:59,217 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 901, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-05-01 02:31:34,436 - root - ERROR - [Errno 20] Not a directory: '/home/nikhil/Desktop/Nikhil/wifi-server/files/index.html'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 216, in start_http_server
    os.chdir(self.server_send_data.text())
NotADirectoryError: [Errno 20] Not a directory: '/home/nikhil/Desktop/Nikhil/wifi-server/files/index.html'
2023-05-01 02:31:53,411 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 400, in create_server
    elif self.broker_process:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-05-01 02:32:07,816 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 901, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-05-01 02:40:28,619 - root - DEBUG - dir fbgbxrgbx does not exist
2023-05-01 02:54:08,493 - root - DEBUG - dir sfvsrf does not exist
2023-05-01 02:54:51,341 - root - DEBUG - dir /home/nikhil/Desktop/Nikhil/wifi-server/files/index.html does not exist
2023-05-01 02:55:24,000 - root - DEBUG - Linking dir /home/nikhil/Desktop/Nikhil/wifi-server/files/
2023-05-01 02:55:35,143 - root - DEBUG - 127.0.0.1 - - [01/May/2023 02:55:35] "GET / HTTP/1.1" 200 -

2023-05-01 02:55:36,013 - root - DEBUG - 127.0.0.1 - - [01/May/2023 02:55:36] code 404, message File not found
127.0.0.1 - - [01/May/2023 02:55:36] "GET /favicon.ico HTTP/1.1" 404 -

2023-05-01 02:56:13,612 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 804, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 885, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:03:11,747 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 804, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 885, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:06:34,063 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 809, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 890, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:10:21,280 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:12345
2023-05-01 03:10:21,282 - root - ERROR - HTTPConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4eade9cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa4eade9cc0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4eade9cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 892, in client_http_get_request
    response = requests.get(http_client_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4eade9cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-05-01 03:12:06,829 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:12345
2023-05-01 03:12:06,832 - urllib3.connectionpool - DEBUG - http://127.0.0.1:12345 "GET / HTTP/1.1" 200 1763
2023-05-01 03:12:06,844 - root - DEBUG - 127.0.0.1 - - [01/May/2023 03:12:06] "GET / HTTP/1.1" 200 -

2023-05-01 03:12:49,860 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:52,435 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:52,867 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:53,227 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:53,475 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:53,707 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:53,923 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:54,139 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:54,339 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:54,531 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:54,731 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:54,939 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:55,155 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:55,363 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:12:56,067 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 808, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:30:30,900 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:12345
2023-05-01 03:30:30,903 - urllib3.connectionpool - DEBUG - http://127.0.0.1:12345 "GET / HTTP/1.1" 200 1763
2023-05-01 03:30:30,914 - root - DEBUG - 127.0.0.1 - - [01/May/2023 03:30:30] "GET / HTTP/1.1" 200 -

2023-05-01 03:31:04,283 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:12345
2023-05-01 03:31:04,286 - urllib3.connectionpool - DEBUG - http://127.0.0.1:12345 "GET / HTTP/1.1" 200 1763
2023-05-01 03:31:04,293 - root - DEBUG - 127.0.0.1 - - [01/May/2023 03:31:04] "GET / HTTP/1.1" 200 -

2023-05-01 03:36:33,260 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:12345
2023-05-01 03:36:33,263 - urllib3.connectionpool - DEBUG - http://127.0.0.1:12345 "GET / HTTP/1.1" 200 1763
2023-05-01 03:36:33,287 - root - DEBUG - 127.0.0.1 - - [01/May/2023 03:36:33] "GET / HTTP/1.1" 200 -

2023-05-01 03:36:48,916 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:12345
2023-05-01 03:36:48,918 - urllib3.connectionpool - DEBUG - http://127.0.0.1:12345 "POST / HTTP/1.1" 501 497
2023-05-01 03:36:48,921 - root - DEBUG - 127.0.0.1 - - [01/May/2023 03:36:48] code 501, message Unsupported method ('POST')
127.0.0.1 - - [01/May/2023 03:36:48] "POST / HTTP/1.1" 501 -

2023-05-01 03:55:59,357 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:00,638 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:02,022 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:02,926 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:03,850 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:04,718 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:05,630 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:06,494 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:08,006 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:08,806 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:09,518 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:10,078 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-05-01 03:56:50,065 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 769, in client_connect_to_server
    self.client_socket.connectToHost(self.client_url, self.client_port)
AttributeError: 'MainWindow' object has no attribute 'client_url'
