2023-04-24 02:44:45,891 - root - DEBUG - 127.0.0.1 - - [24/Apr/2023 02:44:45] "GET / HTTP/1.1" 200 -2023-04-24 03:24:23,399 - root - ERROR - type object 'QProcess' has no attribute 'Running'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 342, in create_server
    if broker_process.state() == QProcess.Running:
AttributeError: type object 'QProcess' has no attribute 'Running'
2023-04-24 03:59:41,699 - root - ERROR - [Errno 13] Permission denied: '/etc/mosquitto/mosquitto.conf'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 360, in create_server
    with open(conf_file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/etc/mosquitto/mosquitto.conf'
2023-04-24 04:02:04,003 - root - ERROR - name 'ip_address' is not defined
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 354, in create_server
    os.system(f"pkexec echo 'listener {ip_address}:{port_number}' > /etc/mosquitto/mosquitto.conf")
NameError: name 'ip_address' is not defined
2023-04-24 04:06:34,953 - root - ERROR - 'PyQt6.QtCore.pyqtBoundSignal' object has no attribute 'start'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 359, in create_server
    self.broker_process.finished.start("mosquito",["-c","/etc/mosquitto/mosquitto.conf"])
AttributeError: 'PyQt6.QtCore.pyqtBoundSignal' object has no attribute 'start'
2023-04-24 04:14:58,473 - root - ERROR - module 'os' has no attribute 'getCwd'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 359, in create_server
    self.broker_process.start("mosquito",["-c",f"{os.getCwd()}/mosquitto.conf"])
AttributeError: module 'os' has no attribute 'getCwd'
2023-04-24 04:22:28,690 - root - ERROR - 'QLineEdit' object has no attribute 'settext'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 354, in create_server
    self.server_ip_input.settext("127.0.0.1")
AttributeError: 'QLineEdit' object has no attribute 'settext'
2023-04-24 04:24:29,054 - root - ERROR - 'NoneType' object has no attribute 'start'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 360, in create_server
    self.server_http_process.start("mosquitto", [ "-p", self.server_port_input.text()])
AttributeError: 'NoneType' object has no attribute 'start'
2023-04-25 06:32:13,894 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect(self.server_ip_input.text(),int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:36:48,876 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:47:11,152 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:53:42,566 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:57:17,138 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 367, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:59:50,017 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 800, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:04:42,047 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 367, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 07:23:52,591 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 809, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:26:05,577 - root - ERROR - 'MainWindow' object has no attribute 'tcp_server'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 382, in create_server
    elif self.tcp_server:
AttributeError: 'MainWindow' object has no attribute 'tcp_server'
2023-04-25 07:55:12,608 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 820, in closeEvent
    self.broker_process.terminate()
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:56:29,664 - root - ERROR - 'MainWindow' object has no attribute 'mqtt_server_client'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 383, in create_server
    self.mqtt_server_client.disconnect()
AttributeError: 'MainWindow' object has no attribute 'mqtt_server_client'
2023-04-25 08:07:53,393 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 835, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:11:21,577 - root - ERROR - wrapped C/C++ object of type QUdpSocket has been deleted
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 384, in create_server
    self.server_udp_socket.deleteLater()
RuntimeError: wrapped C/C++ object of type QUdpSocket has been deleted
2023-04-25 08:11:34,802 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 835, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:14:00,165 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
